services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db

  apigateway:
    image: baronocasiones/gestura-apigateway:dev
    ports: 
      - "8080:8080"
      - "9898:9898"
    restart: always
    depends_on:
      - mongodb
      - signSegmentationService
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - SEGMENTATION_SERVICE_URL=http://signsegmentationservice:8000
      - WEB_SOCKET_HOST=0.0.0.0
      - WEB_SOCKET_PORT=9898

  signSegmentationService:
    image: baronocasiones/gestura-signsegmentationservice:dev
    build:
      context: ./signSegmentationService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always

volumes:
  mongodb_data:
