import { StyleSheet } from 'react-native';

// --- Color Palette ---
export const COLORS = {
  primaryBlue: '#347ae2ff', 
  accentBlue: '#0917b4ff', 
  background: '#535e7eff', 
  textPrimary: '#ffffffff', 
  textSecondary: '#929bf4ff',
  buttonGrey: '#c3c2c2d9',
  white: '#FFFFFF',
  lightBlueCircle: 'rgba(0, 122, 255, 0.15)', 
  dotInactive: '#D1D5DB',
  tapButtonGrey: '#F5F5F5',
  black: '#000',
  darkGrey: '#333',
};

// Base shadow style for reuse
const baseShadow = {
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 3,
  elevation: 2,
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(42, 82, 192, 0.14)',
  },
  content: {
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingVertical: 20,
  },
  titleContainer: {
    marginTop: 130,
    marginBottom: 0,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: COLORS.white,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginTop: 15,
    marginBottom: 180,
    lineHeight: 24,
    maxWidth: '90%',
  },
  dotsContainer: {
    flexDirection: 'row',
    marginTop: 70,
  },
  dot: {
    marginTop: 140,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.dotInactive,
    marginHorizontal: 4,
  },
  dotActive: {
    backgroundColor: COLORS.white,
  },
  bottomActions: {
    paddingHorizontal: 30,
    paddingVertical: 20,
    paddingBottom: 40,
  },
  primaryButton: {
    backgroundColor: COLORS.primaryBlue,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderRadius: 30,
    alignItems: 'center',
    ...baseShadow,
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  primaryButtonText: {
    fontSize: 18,
    color: COLORS.textPrimary,
    fontWeight: 'bold',
  },
  secondaryButton: {
    marginTop: 20,
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 16,
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
});

export const cameraStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.black,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: COLORS.black,
  },
  permissionContainer: {
    flex: 1,
    backgroundColor: COLORS.black,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  permissionMessage: {
    textAlign: 'center',
    paddingBottom: 30,
    color: COLORS.white,
    fontSize: 18,
    lineHeight: 26,
  },
  permissionButton: {
    backgroundColor: COLORS.accentBlue,
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
  },
  permissionButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  cameraContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraFrame: {
    width: '100%',
    marginTop: 70,
    height: 700,
    overflow: 'hidden',
  },
  camera: {
    ...StyleSheet.absoluteFillObject,
  },
  topOverlay: {
    position: 'absolute',
    top: 14,
    left: 18,
    right: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 4,
  },
  statusText: {
    color: COLORS.white,
    fontSize: 22,
    fontWeight: '800',
  },
  subtitleText: {
    color: 'rgba(255, 255, 255, 0.78)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  connectionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 18,
    borderWidth: 1,
  },
  connectionPillConnected: {
    backgroundColor: 'rgba(12, 30, 28, 0.62)',
    borderColor: 'rgba(122, 241, 199, 0.48)',
  },
  connectionPillOffline: {
    backgroundColor: 'rgba(34, 30, 30, 0.62)',
    borderColor: 'rgba(255, 255, 255, 0.24)',
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  connectionDotConnected: {
    backgroundColor: '#7af1c7',
  },
  connectionDotOffline: {
    backgroundColor: '#f8b4aa',
  },
  connectionText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '700',
  },
  cameraFlipButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(10, 14, 24, 0.62)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
  },
  cameraFlipIcon: {
    width: 21,
    height: 21,
    tintColor: COLORS.white,
  },
  previewOverlay: {
    position: 'absolute',
    top: 96,
    left: 0,
    right: 0,
    bottom: 330,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  handGuide: {
    width: '78%',
    maxWidth: 360,
    aspectRatio: 0.78,
    justifyContent: 'center',
    alignItems: 'center',
  },
  guideCorner: {
    position: 'absolute',
    width: 42,
    height: 42,
    borderColor: 'rgba(255, 255, 255, 0.82)',
  },
  guideCornerTopLeft: {
    top: 0,
    left: 0,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderTopLeftRadius: 18,
  },
  guideCornerTopRight: {
    top: 0,
    right: 0,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderTopRightRadius: 18,
  },
  guideCornerBottomLeft: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderBottomLeftRadius: 18,
  },
  guideCornerBottomRight: {
    right: 0,
    bottom: 0,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderBottomRightRadius: 18,
  },
  guideHint: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 22,
    backgroundColor: 'rgba(10, 14, 24, 0.56)',
  },
  guideHintText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  translationContainer: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 108,
    minHeight: 190,
    borderRadius: 28,
    backgroundColor: 'rgba(248, 251, 255, 0.94)',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    ...baseShadow,
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 8,
    zIndex: 3,
  },
  translationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 14,
  },
  translationStatus: {
    color: '#17345f',
    fontSize: 16,
    fontWeight: '800',
  },
  translationHint: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 3,
  },
  captureStatusText: {
    color: '#2563eb',
    fontSize: 11,
    fontWeight: '700',
    maxWidth: 120,
    textAlign: 'right',
  },
  captureStatusError: {
    color: '#dc2626',
  },
  translationContent: {
    minHeight: 72,
    paddingRight: 52,
    justifyContent: 'center',
  },
  translationText: {
    fontSize: 28,
    lineHeight: 34,
    color: '#10233f',
    textAlign: 'left',
    fontWeight: '800',
  },
  placeholderText: {
    fontSize: 22,
    lineHeight: 28,
    color: '#7c8aa1',
    textAlign: 'left',
    fontWeight: '700',
  },
  audioButton: {
    position: 'absolute',
    right: 18,
    bottom: 18,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#e8f0ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  audioButtonActive: {
    backgroundColor: '#2563eb',
  },
  audioButtonIcon: {
    width: 21,
    height: 21,
    tintColor: '#17345f',
  },
  audioButtonIconActive: {
    tintColor: COLORS.white,
  },
  bottomActionsContainer: {
    position: 'absolute',
    bottom: 26,
    left: 18,
    right: 18,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 14,
    zIndex: 4,
  },
  actionButton: {
    backgroundColor: 'rgba(248, 251, 255, 0.92)',
    width: 58,
    height: 58,
    borderRadius: 29,
    justifyContent: 'center',
    alignItems: 'center',
    ...baseShadow,
    shadowOpacity: 0.18,
    shadowRadius: 8,
  },
  actionButtonImage: {
    width: 23,
    height: 23,
    tintColor: '#17345f',
  },
  tapToStartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2563eb',
    borderRadius: 32,
    paddingVertical: 18,
    paddingHorizontal: 32,
    minWidth: 178,
    ...baseShadow,
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 8,
  },
  tapToStartButtonActive: {
    backgroundColor: '#ef4444',
  },
  tapToStartButtonBusy: {
    backgroundColor: '#64748b',
  },
  tapToStartIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
    tintColor: COLORS.white,
  },
  tapToStartIconActive: {
    tintColor: COLORS.white,
  },
  tapToStartText: {
    fontSize: 18,
    color: COLORS.white,
    fontWeight: '800',
  },
  statusDisplayContainer: {
    position: 'absolute',
    top: 80,
    left: 10,
    right: 10,
    backgroundColor: 'rgba(217, 216, 216, 0.72)',
    padding: 10,
    borderRadius: 10,
    borderWidth: 2,
  },
  statusDisplayConnected: {
    borderColor: '#48e6f7ff',
  },
  statusDisplayDisconnected: {
    borderColor: '#ff4444',
  },
  statusDisplayTitle: {
    color: '#f3f3f3ec',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  statusDisplaySession: {
    color: 'white',
    fontSize: 10,
    marginBottom: 3,
  },
  statusDisplayFrame: {
    color: 'white',
    fontSize: 12,
  },
});
